services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: api-senha1
      MYSQL_DATABASE: database_development
      MYSQL_USER: user
      MYSQL_PASSWORD: api-senha1
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_container
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: user
      PMA_PASSWORD: api-senha1
    ports:
      - "8080:80"
    depends_on:
      - mariadb

volumes:
  mariadb_data:
